### ISSUE TITLE
Is it capable of running rosbag data?

### ISSUE THREAD

**Issue by zxd123** [wxliu1/basalt-lwx#1]
中文：
老哥您好，这个版本注释的确实非常详细。非常感谢！想问下这个代码是可以直接跑的嘛？能跑rosbag数据嘛？
English：
Hello, the comments in this version are indeed very detailed. Thank you so much! I wanted to ask, can this code be executed directly? Is it capable of running rosbag data?

**Comment by wxliu1** [comment]
可以跑rosbag数据
